/* eslint-disable no-restricted-globals */
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

self.skipWaiting();
clientsClaim();

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Cache pages and API calls for offline screenshots/demos.
const pageHandler = new StaleWhileRevalidate({
  cacheName: 'fitforge-pages',
});
registerRoute(new NavigationRoute(pageHandler));

registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({ cacheName: 'fitforge-assets' }),
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/test'),
  new StaleWhileRevalidate({ cacheName: 'fitforge-api' }),
);

console.info('FitForge service worker geladen (Workbox aktiv).', { workbox: typeof workbox !== 'undefined' });
